### PR TITLE
Port tests to pytest

### PR DESCRIPTION
**Pull request by janopae**
I wanted to add some tests, but I didn't want to learn the quirks of a custom testing framework that nobody except Trelby uses. Instead, I wanted to get into a testing framework that is widely used in the Python community and learn the quirks of that ;)

I thought about unittest vs pytest, but people keep recommending pytest, so I used that. Also, this made porting the tests easier: As pytests uses mostly the same conventions as our custom test framework, the tests didn't even need to be touched. Only the files needed to be renamed, so they start with `test_`.

By porting to pytest, I got all tests to execute in 0.31s rather than 1.67s on my machine. That's 5.39 times faster.

Also, tests now can be executed from any location (you don't need to `cd` to the tests directory any more).

Also in this PR, I repaired the random test. The random test is a single script that needs to be executed separately, that does some sort of randomised testing towards the UI of trelby (types in random characters and such) and monitors that it doesn't crash. The random test broke in 2019.

### CODE REVIEW

**Comment by limburgher** [comment]
Thank you, this is fantastic!

**Comment by limburgher** [comment]
For me, I need to change to src to run tests.

**Comment by janopae** [comment]
> For me, I need to change to src to run tests.

Oh, interesting. For me, adding src to the `pythonpath` in pyproject.toml (which I committed in 174f534df314aa150ec45126024d848ccd7080bc) did the trick.

On my machine, pytest says
```
rootdir: /home/jano/Projekte/trelby, configfile: pyproject.toml, testpaths: tests
```

when I run `pytest` or `make test` in the root directory of the project. Does it output the same on your machine?

**Comment by limburgher** [comment]
I do. But it's apparently not picking it up.

platform linux -- Python 3.10.6, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/gwyn/dev/trelby, configfile: pyproject.toml, testpaths: tests
plugins: cov-3.0.0, forked-1.4.0, xdist-2.5.0
collected 0 items / 17 errors

**Comment by janopae** [comment]
> platform linux -- Python 3.10.6, pytest-6.2.5, py-1.11.0, pluggy-1.0.0

In requirements.txt, I required a pytest version >7.0 – this was because some issue I had with earlier versions (I'm not sure any more, maybe it even was the fact support for the `pythonpath` key was introduced in 7.0).

Did you install the dependency using `pip install -r requirements.txt`, or did you do it manually?

**Comment by limburgher** [comment]
Ah, right. I'm running pytest as packaged in Fedora 36. We'll get pytest 7 in Fedora 37.

**Comment by limburgher** [comment]
I'll test all this on 37.

**Comment by limburgher** [comment]
Yep, it all works on 37.

**Pull request merged**
